### ISSUE TITLE
How to obtain help ?

### ISSUE THREAD

**Issue by soriacom** [Zimbra-Community/shared-mailbox-toolkit#28]
Hello,
Please can you tell me how to obtain help to install this zimlet. I have try lot of time without sucess. 
Thanks

**Comment by barrydegraaff** [comment]
Go to your Zimbra server using SSH and use the automated installer:

      wget https://raw.githubusercontent.com/Zimbra-Community/shared-mailbox-toolkit/master/shared-mailbox-toolkit-installer.sh -O /tmp/shared-mailbox-toolkit-installer.sh
      chmod +rx /tmp/shared-mailbox-toolkit-installer.sh
      /tmp/shared-mailbox-toolkit-installer.sh

**Comment by soriacom** [comment]
Hello, Thanks, but i have already read all the part for the instalation and i dont arrived to the final. I have errors. I have try to run as root too, i have try to turn of all zimbra services, i have try lot of thing but nothing works. 
When i can obtain more help? Or someone to do this for me. I can pay for. 
Thanks

**Comment by barrydegraaff** [comment]
Okay, you can share the error here or you can send me an ssh login to your server.

You can send me an email at info@barrydegraaff.tk for the login details.

Barry

**Comment by soriacom** [comment]
Thanks. 

Then, when i try to install as root, without stoping zimbra services : 

`Shared Mailbox Toolkit installer
Check if git and zip are installed.
which: no apt-get in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/root/letsencrypt)
Download Shared Mailbox Toolkit to /tmp/shared-mailbox-toolkit-installer.KdKPLLUm
Cloning into 'shared-mailbox-toolkit'...
remote: Enumerating objects: 237, done.
remote: Counting objects: 100% (237/237), done.
remote: Compressing objects: 100% (210/210), done.
remote: Total 237 (delta 11), reused 208 (delta 4), pack-reused 0
Receiving objects: 100% (237/237), 82.10 MiB | 54.66 MiB/s, done.
Resolving deltas: 100% (11/11), done.
Deploy client Zimlet
« tk_barrydegraaff_sharetoolkit_client » -> « /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_sharetoolkit_client »
« tk_barrydegraaff_sharetoolkit_client/tk_barrydegraaff_sharetoolkit_client.js » -> « /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_sharetoolkit_client/tk_barrydegraaff_sharetoolkit_client.js »
« tk_barrydegraaff_sharetoolkit_client/tk_barrydegraaff_sharetoolkit_client.xml » -> « /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_sharetoolkit_client/tk_barrydegraaff_sharetoolkit_client.xml »
Deploy admin Zimlet
[] INFO: Uninstalling Zimlet tk_barrydegraaff_sharetoolkit_admin from LDAP.
[] INFO: Removing Zimlet tk_barrydegraaff_sharetoolkit_admin from COS default
[] INFO: Removing Zimlet tk_barrydegraaff_sharetoolkit_admin from COS defaultExternal
[] INFO: undeploying zimlet tk_barrydegraaff_sharetoolkit_admin
[] INFO: zimlet directory tk_barrydegraaff_sharetoolkit_admin is deleted
  adding: tk_barrydegraaff_sharetoolkit_admin.js (deflated 62%)
  adding: tk_barrydegraaff_sharetoolkit_admin.properties (deflated 40%)
  adding: tk_barrydegraaff_sharetoolkit_admin.xml (deflated 45%)
  adding: ZaShareToolkitTab.js (deflated 73%)
  adding: ZaShareToolkitViewController.js (deflated 57%)
[] INFO: Deploying Zimlet tk_barrydegraaff_sharetoolkit_admin in LDAP.
[] INFO: Installing Zimlet tk_barrydegraaff_sharetoolkit_admin on this host.
[] INFO: Upgrading Zimlet tk_barrydegraaff_sharetoolkit_admin to 0.5.3
[] INFO: Enabling Zimlet tk_barrydegraaff_sharetoolkit_admin
Deploy Java server extension
« extension/ShareToolkit/out/artifacts/ShareToolkit/ShareToolkit.jar » -> « /opt/zimbra/lib/ext/ShareToolkit/ShareToolkit.jar »
Enable X-Authenticated-User header
Deploy CLI tools
« bin/acctalias » -> « /usr/local/sbin/acctalias »
« bin/personagen » -> « /usr/local/sbin/personagen »
« bin/removeshares » -> « /usr/local/sbin/removeshares »
« bin/submachinegun » -> « /usr/local/sbin/submachinegun »
« bin/subzim » -> « /usr/local/sbin/subzim »
« bin/unsubzim » -> « /usr/local/sbin/unsubzim »
Flushing Zimlet Cache
ERROR: service.INVALID_REQUEST (invalid request: can only be used with SOAP)`

When i try to install as root and stop zimbra services before : 

`Shared Mailbox Toolkit installer
Check if git and zip are installed.
which: no apt-get in (/opt/zimbra/bin:/opt/zimbra/common/lib/jvm/java/bin:/opt/zimbra/common/bin:/opt/zimbra/common/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/root/letsencrypt)
Download Shared Mailbox Toolkit to /tmp/shared-mailbox-toolkit-installer.aHcK8eSB
Cloning into 'shared-mailbox-toolkit'...
remote: Enumerating objects: 237, done.
remote: Counting objects: 100% (237/237), done.
remote: Compressing objects: 100% (210/210), done.
remote: Total 237 (delta 11), reused 208 (delta 4), pack-reused 0
Receiving objects: 100% (237/237), 82.10 MiB | 54.07 MiB/s, done.
Resolving deltas: 100% (11/11), done.
Deploy client Zimlet
« tk_barrydegraaff_sharetoolkit_client » -> « /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_sharetoolkit_client »
« tk_barrydegraaff_sharetoolkit_client/tk_barrydegraaff_sharetoolkit_client.js » -> « /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_sharetoolkit_client/tk_barrydegraaff_sharetoolkit_client.js »
« tk_barrydegraaff_sharetoolkit_client/tk_barrydegraaff_sharetoolkit_client.xml » -> « /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_sharetoolkit_client/tk_barrydegraaff_sharetoolkit_client.xml »
Deploy admin Zimlet
[] INFO: Uninstalling Zimlet tk_barrydegraaff_sharetoolkit_admin from LDAP.
[] INFO: master is down, falling back to replica...
[] FATAL: failed to initialize LDAP client
com.zimbra.cs.ldap.LdapException: LDAP error: : An error occurred while attempting to connect to server mail.soriamail.com:389:  java.io.IOException: An error occurred while attempting to establish a connection to server mail.soriamail.com:389:  java.net.ConnectException: Connection refused (Connection refused)
ExceptionId:main:1550605960649:dc520f64a32e6ba2
Code:ldap.LDAP_ERROR
	at com.zimbra.cs.ldap.LdapException.LDAP_ERROR(LdapException.java:90)
	at com.zimbra.cs.ldap.unboundid.UBIDLdapException.mapToLdapException(UBIDLdapException.java:74)
	at com.zimbra.cs.ldap.unboundid.UBIDLdapException.mapToLdapException(UBIDLdapException.java:40)
	at com.zimbra.cs.ldap.unboundid.LdapConnectionPool.createConnPool(LdapConnectionPool.java:117)
	at com.zimbra.cs.ldap.unboundid.LdapConnectionPool.createConnectionPool(LdapConnectionPool.java:63)
	at com.zimbra.cs.ldap.unboundid.UBIDLdapContext.init(UBIDLdapContext.java:111)
	at com.zimbra.cs.ldap.unboundid.UBIDLdapClient.init(UBIDLdapClient.java:39)
	at com.zimbra.cs.ldap.LdapClient.getInstanceIfLDAPavailable(LdapClient.java:62)
	at com.zimbra.cs.ldap.LdapClient.getInstance(LdapClient.java:69)
	at com.zimbra.cs.ldap.LdapClient.initialize(LdapClient.java:94)
	at com.zimbra.cs.account.ldap.LdapProv.<init>(LdapProv.java:47)
	at com.zimbra.cs.account.ldap.LdapProvisioning.<init>(LdapProvisioning.java:291)
	at com.zimbra.cs.account.ldap.LdapProvisioning.<init>(LdapProvisioning.java:288)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.zimbra.cs.account.Provisioning.getInstance(Provisioning.java:354)
	at com.zimbra.cs.account.Provisioning.getInstance(Provisioning.java:310)
	at com.zimbra.cs.zimlet.ZimletUtil.undeployZimletLocally(ZimletUtil.java:778)
	at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1921)
	at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:2010)
Caused by: LDAPException(resultCode=91 (connect error), errorMessage='An error occurred while attempting to connect to server mail.soriamail.com:389:  java.io.IOException: An error occurred while attempting to establish a connection to server mail.soriamail.com:389:  java.net.ConnectException: Connection refused (Connection refused)')
	at com.unboundid.ldap.sdk.LDAPConnection.connect(LDAPConnection.java:754)
	at com.unboundid.ldap.sdk.LDAPConnection.connect(LDAPConnection.java:686)
	at com.unboundid.ldap.sdk.LDAPConnection.<init>(LDAPConnection.java:518)
	at com.unboundid.ldap.sdk.SingleServerSet.getConnection(SingleServerSet.java:229)
	at com.unboundid.ldap.sdk.ServerSet.getConnection(ServerSet.java:98)
	at com.unboundid.ldap.sdk.LDAPConnectionPool.createConnection(LDAPConnectionPool.java:938)
	at com.unboundid.ldap.sdk.LDAPConnectionPool.<init>(LDAPConnectionPool.java:876)
	at com.unboundid.ldap.sdk.LDAPConnectionPool.<init>(LDAPConnectionPool.java:779)
	at com.unboundid.ldap.sdk.LDAPConnectionPool.<init>(LDAPConnectionPool.java:726)
	at com.zimbra.cs.ldap.unboundid.LdapConnectionPool.createConnPool(LdapConnectionPool.java:114)
	... 19 more
Caused by: java.io.IOException: An error occurred while attempting to establish a connection to server mail.soriamail.com:389:  java.net.ConnectException: Connection refused (Connection refused)
	at com.unboundid.ldap.sdk.LDAPConnectionInternals.<init>(LDAPConnectionInternals.java:137)
	at com.unboundid.ldap.sdk.LDAPConnection.connect(LDAPConnection.java:744)
	... 28 more`

Thanks for help

**Comment by soriacom** [comment]
This is the version of linux i use : 

`[root@mail` ~]# uname -a
Linux mail.example.com 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

And the version of Zimbra : 

`[zimbra@mail root]$ zmcontrol -v
Release 8.8.10_GA_3039.RHEL7_64_20180928094617 RHEL7_64 FOSS edition, Patch 8.8.10_P4.`

**Comment by barrydegraaff** [comment]
Your zimbra server does not work properly, it seems the LDAP is down.

What is in your /etc/hosts file?

Especially there should be an entry for mail.soriamail.com. Also give the output of the command `ip a`

**Comment by soriacom** [comment]
in the /etc/hosts file : 

`127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
10.120.2.103 mail.example.com mail`

ip a : 

`[root@mail ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:ee:06:5a brd ff:ff:ff:ff:ff:ff
    inet 10.120.2.103/24 brd 10.120.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.120.2.219/24 brd 10.120.2.255 scope global secondary eth0:0
       valid_lft forever preferred_lft forever
    inet6 fe80::f816:3eff:feee:65a/64 scope link 
       valid_lft forever preferred_lft forever`

**Comment by barrydegraaff** [comment]
Well it seems that you have a connection issue on your zimbra server.

An error occurred while attempting to establish a connection to server mail.soriamail.com:389: java.net.ConnectException: Connection refused (Connection refused)

This should be in /etc/hosts on line 3:

`10.120.2.103 mail.soriamail.com mail`

from https://wiki.zimbra.com/wiki/Ajcody-Hostname-DNS anyway

Also perhaps try and remove that second ip `eth0:0` it maybe the issue

**Comment by soriacom** [comment]
Ok, then, i don't really know ho to do all of this. So you have skype? Perhaps we can work together on this?
Thanks

**Comment by barrydegraaff** [comment]
Skype does not work anymore, you can get an account here: 
[ https://www.freeconferencecall.com/ | https://www.freeconferencecall.com ] 

Then download the app for your desktop 
[ https://www.freeconferencecall.com/global/nl/downloads | https://www.freeconferencecall.com/global/nl/downloads ] 

Then we schedule a meeting tomorrow. What timezone are you in? 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0
